leftnav:
- identifier: 27336534-d1bb-b968-4f13-94e394585355
  name: Instructor Insights
  url: /pages/instructor-insights
  weight: 10
- identifier: external-1175eaab7c134fdbaf066a7b9f5e6d62
  name: Online Publication
  url: https://openlearninglibrary.mit.edu/courses/course-v1:MITx+0.501x+2T2019/about
  weight: 1000
